name: build and publish job

on: push

jobs:
  build-publish:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - name: checkout repository
      uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build source and binary distribution
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: publish to PyPI
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
